@REM @echo off
@REM echo 🟢 Starting MongoDB restore to local...

@REM set BACKUP_DIR=C:\Users\myahm\OneDrive\Desktop\mongo_backup

@REM :: Restore users collections
@REM echo 🔄 Restoring users.streamer...
@REM mongorestore --drop --db=users --collection=streamer "%BACKUP_DIR%\users\streamer.bson"
@REM echo 🔄 Restoring users.admin...
@REM mongorestore --drop --db=users --collection=admin "%BACKUP_DIR%\users\admin.bson"
@REM echo 🔄 Restoring users.billing...
@REM mongorestore --drop --db=users --collection=billing "%BACKUP_DIR%\users\billing.bson"
@REM echo 🔄 Restoring users.counters...
@REM mongorestore --drop --db=users --collection=counters "%BACKUP_DIR%\users\counters.bson"

@REM :: Restore NewMovieDatabase collections
@REM echo 🔄 Restoring NewMovieDatabase.liked...
@REM mongorestore --drop --db=NewMovieDatabase --collection=liked "%BACKUP_DIR%\NewMovieDatabase\liked.bson"
@REM echo 🔄 Restoring NewMovieDatabase.saved...
@REM mongorestore --drop --db=NewMovieDatabase --collection=saved "%BACKUP_DIR%\NewMovieDatabase\saved.bson"
@REM echo 🔄 Restoring NewMovieDatabase.history...
@REM mongorestore --drop --db=NewMovieDatabase --collection=history "%BACKUP_DIR%\NewMovieDatabase\history.bson"
@REM echo 🔄 Restoring NewMovieDatabase.hybridRecommendation2...
@REM mongorestore --drop --db=NewMovieDatabase --collection=hybridRecommendation2 "%BACKUP_DIR%\NewMovieDatabase\hybridRecommendation2.bson"
@REM echo 🔄 Restoring NewMovieDatabase.recommended...
@REM mongorestore --drop --db=NewMovieDatabase --collection=recommended "%BACKUP_DIR%\NewMovieDatabase\recommended.bson"
@REM echo 🔄 Restoring NewMovieDatabase.alsRecommendations...
@REM mongorestore --drop --db=NewMovieDatabase --collection=alsRecommendations "%BACKUP_DIR%\NewMovieDatabase\alsRecommendations.bson"
@REM echo 🔄 Restoring NewMovieDatabase.added...
@REM mongorestore --drop --db=NewMovieDatabase --collection=added "%BACKUP_DIR%\NewMovieDatabase\added.bson"

@REM echo ✅ Full restore completed!
@REM pause